# lyasm/hyprwinter
background #0B1018
foreground #DDEAF7
cursor #FFFFFF

selection_background #263B52
selection_foreground #EAF6FF

color0  #0B1018
color8  #536477

color1  #D45C6A
color9  #F27A86

color2  #79A88D
color10 #9BCDB0

color3  #C5B77A
color11 #E2D49A

color4  #5B8FC4
color12 #80B8F0

color5  #8B78B5
color13 #B19BD9

color6  #5FAFC1
color14 #8ADBEA

color7  #C8D3DE
color15 #F2F7FC
