#max-gamma = 150

#profile {
#    time = 7:30
#    identity = true
#}

#profile {
#    time = 21:00
#    temperature = 5500
#    gamma = 0.8
#}

# Enable blue-light filter
#hyprctl hyprsunset temperature 2500
# Disable blue-light filter
#hyprctl hyprsunset identity

# Set gamma to 50%
#hyprctl hyprsunset gamma 50
# Increase gamma by 10%
#hyprctl hyprsunset gamma +10

# Reset config to current profile
#hyprctl hyprsunset reset
# Reset value to current profile
#hyprctl hyprsunset reset temperature
#hyprctl hyprsunset reset gamma
#hyprctl hyprsunset reset identity

# Print current profile
#hyprctl hyprsunset profile
