#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal # kitty
# exec-once = $browser # brave
exec-once = dunst # notification daemon
exec-once = nm-applet 
exec-once = hyprpaper # background
exec-once = waybar # top bar
exec-once = copyq # clipboard manager
exec-once = gnome-keyring-daemon --start --components=secrets # git
exec-once = hyprsunset
# exec-once = sh -c '
# sleep 1
# killall -e xdg-desktop-portal-hyprland
# killall xdg-desktop-portal
# /usr/lib/xdg-desktop-portal-hyprland &
# sleep 2
# /usr/lib/xdg-desktop-portal &
# '
