#preload = /home/penguinerd/Pictures/Naruto/Naruto0001.jpg
#wallpaper = ,/home/penguinerd/Pictures/Naruto/Naruto0001.jpg

wallpaper {
    monitor = 
    path = ~/Pictures/Hypr/winter5.png
    fit_mode = cover
}
