exec-once = dunst
exec-once = nm-applet 
exec-once = copyq 

exec-once = gnome-keyring-daemon --start --components=secrets # git
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 # vpn? idk

# rice
exec-once = waybar 

# hypr ecosystem
exec-once = hyprpaper 
exec-once = hyprsunset
exec-once = hypridle
