#preload = /home/penguinerd/Pictures/Naruto/Naruto0001.jpg
#wallpaper = ,/home/penguinerd/Pictures/Naruto/Naruto0001.jpg

wallpaper {
    monitor = 
#    path = ~/Pictures/Naruto/Naruto0001.jpg
    fit_mode = cover
}
